name: Build and Upload to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --noconsole auto_git_commit.py
          ls -la dist

      - name: Prepare Package for GitHub Packages
        run: |
          mkdir -p package-linux
          mv dist/auto_git_commit package-linux/
          echo '{"name":"auto-git-commit-linux","version":"1.0.0"}' > package-linux/package.json

      - name: Publish to GitHub Packages (Linux)
        run: npm publish --access public ./package-linux/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --noconsole auto_git_commit.py
          ls -la dist

      - name: Prepare Package for GitHub Packages
        run: |
          mkdir -p package-windows
          mv dist/auto_git_commit.exe package-windows/
          echo '{"name":"auto-git-commit-windows","version":"1.0.0"}' > package-windows/package.json

      - name: Publish to GitHub Packages (Windows)
        run: npm publish --access public ./package-windows/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
